from ROOT import *
LineColor = RooFit.LineColor
htree = TFile.Open("root_real_data.root").Get("DecayTree")
histo = TH1F("histo","plotOn test histo",1000,1830,1900)
for entry in htree:
	histo.Fill(entry.D_M)
x = RooRealVar("x","x",1830,1900)
x2 = RooRealVar("x2","x2",-3,3)
m = RooRealVar("m","m test",300)
s = RooRealVar("s","s test",500)
a = RooRealVar("a","a test",0.0001,0.0002,0.0)
t = RooRealVar("t","t",0,2)
tshift = RooRealVar("thshift","tshift",0)
alpha = RooRealVar("alpha","alpha",100)
vlambda = RooRealVar("lambda","lambda",1)
g1frac = RooRealVar("g1frac","g1frac test",0.3*2700000,1,3000000)
g2frac = RooRealVar("g2frac","g2frac test",0.05*2700000,1,3000000)
hdata = RooDataHist("data","plotOn test data with x",RooArgList(x),histo)
m.setConstant(kFALSE)
s.setConstant(kFALSE)
vlambda.setConstant(kFALSE)
model = RooGaussian("model","gauss test",x,m,s)
model2 = RooExponential("model2","exponential test",x,a)
modelsum = RooAddPdf("modelsum","model+model2",RooArgList(model,model2),RooArgList(g1frac,g2frac))
frame = x.frame()
modelsum.fitTo(hdata)
hdata.plotOn(frame)
hdata.statOn(frame)
modelsum.paramOn(frame)
modelsum.plotOn(frame,LineColor(kRed))
frame.Draw()
