from ROOT import *
x = RooRealVar("x","x",-10,10)
mean = RooRealVar("mean","mean of gaussian",-1)
sigma = RooRealVar("sigma","width of gaussian",3)
gauss = RooGaussian("gauss","gaussian PDF",x,mean,sigma)
data = gauss.generate(RooArgSet(x), 10000)
mean.setConstant(kFALSE)
sigma.setConstant(kFALSE)
gauss.fitTo(data)
xframe = x.frame()
data.plotOn(xframe, RooLinkedList())
gauss.plotOn(xframe)
xframe.Draw()
mean.Print()
sigma.Print()
